#!/bin/sh -f
SCRIPT_DIR=`dirname $0`
java -Xms15G -cp "$COATJAVA/lib/clas/*:$SCRIPT_DIR/target/*" org.jlab.clas.analysis.clary.phiAnalysis $*
#java -Xms1024m -cp "$COATJAVA/lib/clas/*:$SCRIPT_DIR/target/*" org.jlab.clas.analysis.clary.phiAnalysis $*
